# define the search space here, parameters must be part of the ModelConfig
# PatchTST
model:
  d_ff: 'tune.choice([128, 256, 512])'
  d_model: 'tune.choice([64, 128, 256])'
  e_layers: 'tune.choice([2, 3, 4])'

