# QUITO Training Configuration
# This file contains all training parameters for time series forecasting models

# Data Configuration
data:
  common:
    data_dir: "/ossfs/workspace/ts_data_parquet"
    seq_len: 512  # Input sequence length
    decoder_label_len: 48  # Label length for decoder start
    forecast_horizon: 96  # Prediction length
    features: "M"  # M: multivariate->multivariate, S: univariate->univariate, MS: multivariate->univariate
    normalize: True
  datasets:
    TEST_DATA: 
      file_name: "/ossfs/workspace/ts_data_parquet/test_data.parquet"
      train_ratio: 0.7
      valid_ratio: 0.2
      test_ratio: 0.1
      is_pretrain: True
      freq: 'M'
      ds_cls: 'TimeSeriesDataset'
      ds_kwargs: {}
      target: 'ind_1'
    # MIN_P1: 
      # file_name: "train_min_p1.parquet"
      # train_ratio: 0.8
      # valid_ratio: 0.1
      # test_ratio: 0.1
      # is_pretrain: True
      # freq: 'M'
      # ds_cls: 'TimeSeriesDataset'
      # ds_kwargs: {}
      # target: 'ind_1'
      # anomaly_remove_method: null
      # na_impute_method: 'linear'
    # MIN_P2: 
    #   file_name: "train_min_p2.parquet"
    #   train_ratio: 0.8
    #   valid_ratio: 0.1
    #   test_ratio: 0.1
    #   is_pretrain: True
    #   freq: 'M'
    #   ds_cls: 'TimeSeriesDataset'
    #   ds_kwargs: {}
    #   target: 'ind_1'
      # anomaly_remove_method: 'stl'
      # na_impute_method: 'linear'
    # MIN_P3: 
    #   file_name: "train_min_p3.parquet"
    #   train_ratio: 0.8
    #   valid_ratio: 0.1
    #   test_ratio: 0.1
    #   is_pretrain: True
    #   freq: 'M'
    #   ds_cls: 'TimeSeriesDataset'
    #   ds_kwargs: {}
    #   target: 'ind_1'
    #   anomaly_remove_method: 'stl'
    #   na_impute_method: 'linear'
    # MIN_P4: 
    #   file_name: "train_min_p4.parquet"
    #   train_ratio: 0.8
    #   valid_ratio: 0.1
    #   test_ratio: 0.1
    #   is_pretrain: False
    #   freq: 'M'
    #   ds_cls: 'TimeSeriesDataset'
    #   ds_kwargs: {}
    #   target: 'ind_1'
    #   anomaly_remove_method: 'stl'
    #   na_impute_method: 'linear'

# Model Configuration
model:
  # model_name: 'dlinear'
  model_name: "tstransformer"  # Model architecture: pyraformer, informer, autoformer, patchtst
  time_pe_type: null
  feature_pe_type: null
  d_model: 512
  layers: ['feature_full', 'time_full', 'feature_full', 'time_full']
  # d_model: 16  # Model dimension
  # n_heads: 8  # Number of attention heads
  # d_ff: 128  # Dimension of feedforward network
  # dropout: 0.3  # Dropout rate
  # activation: "gelu"  # Activation function
  # norm: 'layer'
  # patch_len: 16
  # stride: 8

# Training Configuration
training:
  trainer_name: 'trainer' # which trainer class to use ? default to Trainer
  num_epochs: 100  # Number of training epochs
  batch_size: 32  # Training batch size per device
  eval_batch_size: 32  # Evaluation batch size (if null, uses batch_size)
  learning_rate: 0.001  # Learning rate
  weight_decay: 0.0  # Weight decay for regularization
  warmup_ratio: 0.0  # Warmup ratio (0.0 to 1.0)
  gradient_accumulation_steps: 1  # Number of gradient accumulation steps should >= 1
  max_grad_norm: 0.0  # Max gradient norm for clipping
  seed: 16  # Random seed for reproducibility
  num_workers: 6
  pin_memory: True
  shuffle: True
  save_last_k: 10
  loss: 'mse'
  loss_kwargs: {}
  drop_last: True

# Optimization Configuration
optimization:
  fp16: False  # Use mixed precision training (FP16)
  num_workers: 4  # Number of data loading workers
  scheduler: "cosine"  # Learning rate scheduler
  scheduler_kwargs: {
    T_max: 100,
    eta_min: 0.0001
  }
  optimizer: "adam"  # Optimizer
  optimizer_kwargs: {}

# checkpointing
checkpointing:
  save_last_k: 10
  save_steps: null  # Save checkpoint every N steps, None if dont want to save at step
  save_epochs: 1 # Save checkpoint every N epochs, None if dont want to save at epoch
  

# Logging Configuration
logging:
  output_dir: "outputs"  # Output directory for checkpoints and logs
  logging_steps: 100  # Log every N steps, None if dont want to log training measures at steps
  logging_epochs: 1 # log every N epochs, None if dont want to log training measures at epoch
  sync_loss: False # If true, training loss will be synced across devices
  sync_score: True # If true, validation score will be synced across devices

# Early Stopping Configuration
early_stopping:
  enable_early_stopping: False  # Enable early stopping
  early_stopping_patience: 5  # Number of evaluations with no improvement before stopping
  es_metric: "mse"  # Metric to monitor for early stopping
  greater_is_better: False  # is_greater_better for the metric

evaluation:
  eval_metrics: ['mse', 'mae']
  eval_steps: 10000  # Evaluate every N steps,  None if dont want to eval at steps
  eval_epochs: 1 # Evaluate every N epochs, None if dont want to eval at epoch
  save_eval_results_top_k: 10 # wheather to save the last k eval step results, the inputs, predictions and labels during evaluation
# Resume Training
resume:
  checkpoint_path: null  # Path to checkpoint to resume from (if null, start from scratch)

distributed:
  ddp_find_unused_parameters: True
  ddp_backend: "nccl"

